version: '3.7'

services:
  web:
    build:
      context: ./thepacketwizards
      dockerfile: Dockerfile
    command: gunicorn thepacketwizards.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static_root
      - media_volume:/home/app/web/media_root
    expose:
      - 8000
    env_file:
      - ./env/web.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/db.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static_root
      - media_volume:/home/app/web/media_root
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: