version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn thepacketwizards.wsgi:application --bind [::]:8000
    volumes:
      - static_volume:/home/app/web/static_root
      - media_volume:/home/app/web/media_root
    expose:
      - 8000
    env_file:
      - ./env/web.prod
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/db.prod
    restart: always
  nginx:
   build:
     context: ./nginx
     dockerfile: Dockerfile
   volumes:
     - static_volume:/home/app/web/static_root
     - media_volume:/home/app/web/media_root
     - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
     - /home/decastromonteiro/letsencrypt/live/thepacketwizards.com/fullchain.pem:/etc/letsencrypt/live/thepacketwizards.com/fullchain.pem
     - /home/decastromonteiro/letsencrypt/live/thepacketwizards.com/privkey.pem:/etc/letsencrypt/live/thepacketwizards.com/privkey.pem
     - /home/decastromonteiro/letsencrypt/letsencrypt-site:/data/letsencrypt
   ports:
     - 80:80
     - 443:443
   restart: always
   depends_on:
     - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
