# Generated by Django 2.2.7 on 2019-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='series_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
