# Generated by Django 2.2.7 on 2019-11-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191107_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default='uncategorized', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogCategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogSeries'),
        ),
    ]
